from thebeautyofdata import Canvas
from thebeautyofdata import DataHandler
from thebeautyofdata import Date
from thebeautyofdata import StaticImage
from thebeautyofdata import StaticText
from thebeautyofdata import Axis
from thebeautyofdata import Legend
from thebeautyofdata import LineChart
from thebeautyofdata import Total
